name: Build Zed Nightly

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight UTC
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        backend: [vulkan, opengl]
        include:
          - backend: vulkan
            artifact_name: zed-debug
            rustflags: ""
          - backend: opengl
            artifact_name: zed-debug-opengl
            rustflags: "--cfg gles"

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: lhutyra/zed
          ref: main
          path: zed

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend }}
          workspaces: "zed -> target"

      - name: Setup rustflags
        shell: pwsh
        run: ./Parse-Rustflags.ps1 ${{ matrix.rustflags }}

      - name: Build debug
        working-directory: zed
        run: cargo build  # Budowanie w trybie debug (bez --release)

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: zed/target/debug/zed.exe  # Poprawiona ścieżka dla debug

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create release directories and zip
        run: |
          mkdir -p zed-debug zed-debug-opengl
          mv artifacts/zed-debug/zed.exe zed-debug/
          mv artifacts/zed-debug-opengl/zed.exe zed-debug-opengl/
          zip -r zed-windows-debug.zip zed-debug/*
          zip -r zed-windows-debug-opengl.zip zed-debug-opengl/*

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: |
            zed-windows-debug.zip
            zed-windows-debug-opengl.zip
